"""add forum activity tables

Revision ID: 42f5d054e245
Revises: 106bfe752b75
Create Date: 2026-08-24 15:43:02.153914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "42f5d054e245"
down_revision: Union[str, None] = "106bfe752b75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forum_backfill_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("forum", sa.String(length=50), nullable=False),
        sa.Column(
            "earliest_month_backfilled", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "last_incremental_refresh_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "categories_cache", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("categories_cached_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forum"),
    )
    op.create_table(
        "forum_topics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("forum", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("posts_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("forum", "external_id"),
    )
    op.create_index(
        op.f("ix_forum_topics_category"), "forum_topics", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_forum_topics_created_at"), "forum_topics", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_forum_topics_forum"), "forum_topics", ["forum"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_forum_topics_forum"), table_name="forum_topics")
    op.drop_index(op.f("ix_forum_topics_created_at"), table_name="forum_topics")
    op.drop_index(op.f("ix_forum_topics_category"), table_name="forum_topics")
    op.drop_table("forum_topics")
    op.drop_table("forum_backfill_state")
    # ### end Alembic commands ###
