---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart craft-dashboard
  ansible.builtin.systemd:
    name: craft-dashboard
    state: restarted

- name: Restart collect-data
  ansible.builtin.shell: systemctl restart --no-block collect-data
  failed_when: false
